interface Node {
  id: ID!
}

type Location {
  lng: Float!,
  lat: Float!
}

input LocationInput {
  lng: Float!,
  lat: Float!
}

scalar Email

type PageInfo {
  hasNextPage: Boolean!
  hasPreviousPage: Boolean!
  startCursor: ID
  endCursor: ID
}
